language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on:
    branch: master
    repo: pekoe09/malvamern
  bucket: malva-deploy
  region: eu-central-1
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: malva-deploy
  key: latest.zip
  bundle_type: zip
  application: CodeDeployMalva
  deployment_group: MalvaDeploymentGroup
  region: eu-central-1
  on:
    branch: master
script:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip